### ISSUE TITLE
[issue] outdated link on github description

### ISSUE THREAD

**Issue by naufalafif** [pod-III/quick-write#1]
## Description:
wrong link on github description.

current: https://quick-write-mu.vercel.app/
expected: https://quickwrite.vercel.app/

## Screenshoot
![Screenshot 2023-08-27 060137](https://github.com/pod-III/quick-write/assets/12013083/bf68a4d4-3afd-4215-b1cd-b4b26c22362e)

cc @pod-III

**Comment by pod-III** [comment]
link changed
